version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 5s
      retries: 5

  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["go", "test", "./handler", "./repository", "-count=1", "-timeout=60s", "-v"]

volumes:
  db_data:
