basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Simple wallet deposit/withdraw service.
  title: Wallet Service API
  version: "1.0"
paths:
  /wallet:
    post:
      consumes:
      - application/x-www-form-urlencoded
      - application/json
      description: Performs a deposit or withdrawal on a wallet
      parameters:
      - description: Wallet ID
        in: formData
        name: walletId
        required: true
        type: string
      - description: Operation Type
        enum:
        - DEPOSIT
        - WITHDRAW
        in: formData
        name: operationType
        required: true
        type: string
      - description: Amount (must be > 0)
        in: formData
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: no content
        "400":
          description: invalid request or amount must be positive
          schema:
            type: string
        "409":
          description: insufficient funds
          schema:
            type: string
        "500":
          description: server error
          schema:
            type: string
      summary: Deposit or withdraw money
      tags:
      - wallets
  /wallets/{id}:
    get:
      description: Returns the current balance for a given wallet ID
      parameters:
      - description: Wallet UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "500":
          description: server error
          schema:
            type: string
      summary: Get wallet balance
      tags:
      - wallets
swagger: "2.0"
